### ISSUE TITLE
Returns false when nothing is matched

### ISSUE THREAD

**Issue by pmarkert** [peter-valkov/advanced-json-path#1]
I was considering replacing the jsonpath engine in https://github.com/pmarkert/hyperpotamus with this one, however, I noticed that if the expression fails to match anything, the engine returns false which is indistinguishable from succesfully matching and returning a value of false. Any chance you could have it raise an error if there are no matches instead?

**Comment by peter-valkov** [comment]
Good point. I'll see what I can do.
