### ISSUE TITLE
Filter on json elements named '$'

### ISSUE THREAD

**Issue by brendon-stephens** [peter-valkov/advanced-json-path#2]
Hi Peter

I am wondering if it is possible to filter on a json element named "$". It seems to be causing issues, I suspect due to conflicts with the root element. I have also tried using the bracket notation which returned similar results. 

Are you able to assist?

Thanks!

```javascript
var object = {
    "EventURL": "/mod-tc-mk2",
    "EventData": {
        "Device": "MOD-TC-MK2",
        "Status": "OK",
        "Data": {
            "$": "FindMe"
        },
        "I2C_Address": "0x23"
    }
}
var path = "$..EventData[?(@.Data.$=='FindMe')]";
var result = JSONPath(object, path);
```

**Comment by peter-valkov** [comment]
In this case you can use nested JSONPath expression. Try this
`$..EventData[?({Data['$']}=='FindMe')]`

**Comment by brendon-stephens** [comment]
Thanks Peter - works perfectly!

**Comment by brendon-stephens** [comment]
Could I trouble you with another syntax issue I am having.... how can I match on "I2C:Address" (changed underscore to colon)

```javascript
var object = {
    "EventURL": "/mod-tc-mk2",
    "EventData": {
        "Device": "MOD-TC-MK2",
        "Status": "OK",
        "Data": {
            "$": "FindMe"
        },
        "I2C:Address": "0x23"
    }
}
var path = "$..['I2C:Address']";
var result = JSONPath(object, path);
```

**Comment by peter-valkov** [comment]
I am just curious - why the hell you need such names

`$..EventData['I2C:Address']`
`$..[?({['I2C:Address']})]['I2C:Address']`

**Comment by brendon-stephens** [comment]
That's an interesting one - thanks! 

I am querying JSON data which has been transformed from XML documents - as such leaf elements are represented as "$" and any namespaces are also transformed across. There's probably issues with the xml to json transform, but for now that's out of my control.

**Comment by peter-valkov** [comment]
A better solution
`..('I2C:Address')`

**Comment by brendon-stephens** [comment]
I have one last question (sorry to bug you!). Are you able to provide an example on how this should be structured? Functions which accept no parameters seem to work fine (eg. length) but those which need a parameter aren't working (eg. indexOf). 

```javascript
var object = {
    "EventURL": "/mod-tc-mk2",
    "EventData": {
        "Device": "MOD-TC-MK2",
        "Status": "OK",
        "Data": {
            "$": "FindMe"
        },
        "I2C:Address": "0x23"
    }
}
var path = "$..Data[?({['$']}.indexOf('No') == -1)]"; // does not work
var path = "$..Data[?({['$']}.indexOf('Me') > 0)]"; // does not work
var path = "$..Data[?({['$']}.length == 6)]"; // works
var result = JSONPath(object, path);

```

**Comment by peter-valkov** [comment]
You can query properties of javascript objects and can not call their methods. `length` is property of String as you can see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length) That's why it is working. 

In your example you should check if there is occurrence of 'Me' in your code
```javascript
var object = {
    "EventURL": "/mod-tc-mk2",
    "EventData": {
        "Device": "MOD-TC-MK2",
        "Status": "OK",
        "Data": {
            "$": "FindMe"
        },
        "I2C:Address": "0x23"
    }
};
var path = "..('$')"; 
var result = JSONPath(object, path);
if (typeof result == 'string' && result.indexOf('Me') != -1) {
    // your code here
}
```
